# Shiny Server configuration for Codeface
# Run as the shiny user
run_as shiny;

# Define a server that listens on port 8081
server {
  listen 8081;

  # Define the location for the Shiny apps
  location / {
    # Host the directory of Shiny apps
    site_dir /app/codeface/R/shiny/apps;
    
    # Log directory
    log_dir /app/log/shiny-server;
    
    # Directory index - show available apps
    directory_index on;
  }
}
